apiVersion: v1
kind: Service
metadata:
  name: usersearchapp-service
spec:
  type: NodePort
  selector:
    app: usersearchapp  
  ports:
  - port: 4200
    targetPort: 80
    nodePort: 31000
    protocol: TCP
